defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private_no.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .
name: "cam256-dino-vit" # change here for cifar100
method: "dino"
backbone:
  name: "vit_small"
  kwargs:
    patch_size: 16
    img_size: 256
    pretrained: True
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  norm_last_layer: False
momentum:
  base_tau: 0.996
  final_tau: 1.0
data:
  dataset: custom
  train_path: "/gpfsscratch/rech/rnz/uyc98hc/camelyon256/train"
  no_labels: True
  val_path: ""
  format: "dali"
  num_workers: 1
optimizer:
  name: "adamw"
  batch_size: 128
  lr: 0.0005
  classifier_lr: 1e-4
  weight_decay: 0.004
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 300


# overwrite PL stuff
max_epochs: 200
devices: [0,1,2,3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
num_nodes: 2