defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private_no.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "cam256-dino-res" # change here for cifar100
method: "dino"
backbone:
  name: "resnet18"
  pretrained: True

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 4096
momentum:
  base_tau: 0.996
  final_tau: 1.0
data:
  dataset: custom
  train_path: "/gpfsscratch/rech/rnz/uyc98hc/camelyon256/train"
  no_labels: True
  val_path: ""
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 3000
auto_umap:
    enabled: False

# overwrite PL stuff
max_epochs: 200
devices: [0,1,2,3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
