defaults:
  - _self_
  - augmentations: symmetric_weak.yaml
  - wandb: private_no.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "cam20xf1-simclr-res50v1"
method: "simclr"
backbone:
  name: "resnet50"
  pretrained: True
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 512
  temperature: 0.5
data:
  dataset: custom
  train_path: "/gpfsscratch/rech/rnz/uyc98hc/cam20x/train"
  no_labels: True
  val_path: ""
  format: "dali"
  # image_folder
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.3 # 4x
  classifier_lr: 0.00001
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 3000

max_epochs: 80
devices: [0,1,2,3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
num_nodes: 2
