defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private_no.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mel-byol-vit"
method: "byol"
backbone:
  name: "vit_small"
  kwargs:
    patch_size: 16
    img_size: 256
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: "custom"
  train_path: "/gpfsscratch/rech/rnz/uyc98hc/melanoma/train"
  val_path: ""  # remove this if there's no validation dir
  format: "dali" # data format, supports "image_folder", "dali" or "h5"
  num_workers: 4
  no_labels: True
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.0001
  classifier_lr: 0.005
  weight_decay: 0.05
  kwargs:
    clip_lr: True
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 3000
# overwrite PL stuff
max_epochs: 200
devices: [0,1,2,3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
num_nodes: 2